EXTRN	DISPBX:FAR
MYDATA SEGMENT
DATA  	DW      1234H,5678H,9D4CH,0D7H,8A0EH,0,-1,7D2AH,10F5H,645DH
N   	EQU     	$-DATA
MYDATA ENDS
CODE    	SEGMENT
        	ASSUME  CS:CODE,DS:MYDATA
MAIN	PROC	FAR
	PUSH	DS
	MOV	AX,0
	PUSH	AX
 	MOV     AX,MYDATA
       	 MOV     DS,AX      ;装填DS
MOV    	 CX,N-1
MOV     	BX,OFFSET DATA
MOV	AX,WORD PTR [BX]     ;因为是十六位，所以转换格式，将前面的数放入AX
AGAIN:   	ADD	BX,2
	MOV	DX, WORD PTR [BX]		;将后面的数放入DX
	TEST	DX,1	;判断此数是否是奇数
	JNZ	NEXT	;是的话直接跳到NEXT
	CMP	AX,DX	;是偶数的话比较大小
	JLE	NEXT
	MOV	AX,DX
NEXT:	LOOP	AGAIN
	MOV	BX,AX
	CALL	DISPBX	;调用子程序显示
	MOV	AH,2
	MOV	DL,48H
	INT	21H
	RET
MAIN	ENDP

CODE	ENDS
END	MAIN

